In [3]:
import numpy as np
a = np.array([1,2,3,4])
print("1D array :-", a)
type(a)

1D array :- [1 2 3 4]


numpy.ndarray

In [12]:
b = np.array([[1,2],[3,4]])
print("2D array OR Vectors :-")
print( b)
type(b)

2D array OR Vectors :-
[[1 2]
 [3 4]]


numpy.ndarray

In [11]:
c = np.array([[[1,2],[3,4],[5,6]]])
print("3D array OR Matrix :-")
print(c)

3D array OR Matrix :-
[[[1 2]
  [3 4]
  [5 6]]]


In [13]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensior :-")
print(d)

tensior :-
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
e = np.array([1,2,3,4], dtype = float)
print(e)

[1. 2. 3. 4.]


In [16]:
f = np.array([1,2,3,4], dtype = bool)
print(f)

[ True  True  True  True]


In [19]:
f = np.array([1,2,3,4], dtype = bool)
print(f)

[ True  True  True  True]


In [20]:
f = np.array([1,2,3,4], dtype = complex)
print(f)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [29]:
# np.arange ( works as loop)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(1,50,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [33]:
np.arange(1,21).reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [34]:
np.arange(1,21).reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [40]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a = np.array([1.0, 2.0, 3.0])# will it return float or int type numbers?
print(a)
type(a)

[1. 2. 3.]


numpy.ndarray

In [8]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.ones((5,12))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# 

#pip install pygwalker

Note: you may need to restart the kernel to use updated packages.


In [6]:
##

#import pygwalker as pyg

In [9]:
np.random.random((3,3))

array([[0.96847675, 0.35097951, 0.69895904],
       [0.28921332, 0.26708407, 0.74014502],
       [0.75350513, 0.09581411, 0.30267876]])

In [13]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [17]:
#ndim
a3.ndim

3

In [20]:
a2.ndim

2

In [18]:
# shape
a1.shape

(10,)

In [21]:
a2.shape

(3, 4)

In [27]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
# size
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
# itemsize
a3.itemsize

4

In [34]:
print(a3.itemsize)
a3

4


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


changing data types

In [36]:
# astype
a3.dtype

dtype('int32')

In [39]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

##Array operations

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [42]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
# scaler operations
# arithmatic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
# retaional
a2> 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
# vector operations
# airthmatic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [52]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [53]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

In [54]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [55]:
## Array function

In [62]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[68., 77., 44.],
       [84., 61., 58.],
       [22., 19., 27.]])

In [64]:
a1

array([[68., 77., 44.],
       [84., 61., 58.],
       [22., 19., 27.]])

In [65]:
# max / min / sum / prod
np.max(a1)

84.0

In [66]:
np.min(a1)

19.0

In [67]:
np.sum(a1)

460.0

In [68]:
np.prod(a1)

772733027582208.0

In [69]:
# 0 ->(means) col and 1 ->(means)rows
np.max(a1,axis=0)

array([84., 77., 58.])

In [72]:
np.max(a1,axis=1)

array([77., 84., 27.])

In [73]:
np.min(a1,axis=1)

array([44., 58., 19.])

In [74]:
np.min(a1,axis=0)

array([22., 19., 27.])

In [75]:
np.sum(a1,axis=1)

array([189., 203.,  68.])

In [76]:
np.sum(a1,axis=0)

array([174., 157., 129.])

In [77]:
np.prod(a1,axis=1)

array([230384., 297192.,  11286.])

In [78]:
np.prod(a1,axis=0)

array([125664.,  89243.,  68904.])

In [79]:
# mean / median / std / var
np.mean(a1)

51.111111111111114

In [80]:
np.mean(a1,axis=0)

array([58.        , 52.33333333, 43.        ])

In [81]:
np.mean(a1,axis=1)

array([63.        , 67.66666667, 22.66666667])

In [82]:
np.median(a1,axis=0)

array([68., 61., 44.])

In [83]:
np.median(a1,axis=1)

array([68., 61., 22.])

In [84]:
np.std(a1,axis=0)

array([26.28053779, 24.45858177, 12.67543556])

In [85]:
np.std(a1,axis=1)

array([13.92838828, 11.61416759,  3.29983165])

In [86]:
np.var(a1,axis=0)

array([690.66666667, 598.22222222, 160.66666667])

In [87]:
np.var(a1,axis=1)

array([194.        , 134.88888889,  10.88888889])

In [88]:
# trignomatric function
np.sin(a1)

array([[-0.89792768,  0.99952016,  0.01770193],
       [ 0.73319032, -0.96611777,  0.99287265],
       [-0.00885131,  0.14987721,  0.95637593]])

In [89]:
np.cos(a1)

array([[ 0.44014302, -0.03097503,  0.99984331],
       [-0.6800235 , -0.25810164,  0.11918014],
       [-0.99996083,  0.98870462, -0.29213881]])

In [93]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [94]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [95]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [97]:
# log and exponent
np.log(a1)

array([[4.21950771, 4.34380542, 3.78418963],
       [4.4308168 , 4.11087386, 4.06044301],
       [3.09104245, 2.94443898, 3.29583687]])

In [98]:
np.exp(a1)

array([[3.40427605e+29, 2.75851345e+33, 1.28516001e+19],
       [3.02507732e+36, 3.10429794e+26, 1.54553894e+25],
       [3.58491285e+09, 1.78482301e+08, 5.32048241e+11]])

In [104]:
# round(roundoff value)/ floor(back value) / ceil(next value)
np.random.random((2,3))*100

array([[91.00301376, 14.92645161, 66.83867688],
       [29.65097811, 90.53348423, 34.27438477]])

In [105]:
np.round(np.random.random((2,3))*100)

array([[ 16.,  14.,   8.],
       [100.,  76.,  28.]])

In [106]:
np.floor(np.random.random((2,3))*100)

array([[71., 96., 82.],
       [36., 65., 15.]])

In [108]:
np.ceil(np.random.random((2,3))*100)

array([[36., 37., 86.],
       [89.,  5., 51.]])

## indexing and slicing

In [2]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [3]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [4]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1[-1]

9

In [7]:
a1[0]

0

In [8]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# find value from 2D 
# if we want 6 from above data 
a2[1,2]
# here 1 denotes row no.& 2 denotes column

6

In [11]:
a2[2,3]

11

In [12]:
a2[1,0]

4

In [13]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# find value from tensior
# if we want 5 from above data
a3[1,0,1]
# here 1 denotes from which tensior 0 denotes row &1 denotes column

5

In [17]:
a3[0,1,0]

2

In [18]:
a3[0,0,0]

0

In [19]:
a3[1,1,0]

6

In [20]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a1[2:5]

array([2, 3, 4])

In [22]:
a1[2:5:2]

array([2, 4])

In [23]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2[0,:]

array([0, 1, 2, 3])

In [25]:
a2[:,2]

array([ 2,  6, 10])

In [27]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [28]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [40]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
a2[1::2,::3]

array([[4, 7]])

In [69]:
a2[0:2,1::1]

array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [9]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [10]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [14]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
a3[0,1]

array([3, 4, 5])

In [21]:
a3[1,:,1]

array([10, 13, 16])

In [23]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [41]:
a3[0,0,0::2]

array([0, 2])

In [40]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## iterating

In [46]:
a1
for i in a1:
    print(i,end =' ')

0 1 2 3 4 5 6 7 8 9 

In [48]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [49]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [52]:
for i in np.nditer(a3):
    print(i,end =' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

## Transpose

In [53]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [54]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## ravel

In [56]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## stacking (combine)

In [59]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [60]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [63]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## splitting

In [64]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [67]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [71]:
# vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [72]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]