In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# np.sort

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [5]:
a = np.random.randint(1,100,15)
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [6]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 6, 40, 84, 95],
       [43, 51, 85, 71],
       [88, 36, 11, 17],
       [13, 90, 77, 49],
       [94, 66, 88, 42],
       [73,  2, 81,  1]])

In [7]:
np.sort(a)

array([ 1,  9, 19, 21, 24, 27, 56, 57, 73, 79, 84, 91, 91, 93, 94])

In [9]:
# sort by column bydefault
np.sort(b)

array([[ 6, 40, 84, 95],
       [43, 51, 71, 85],
       [11, 17, 36, 88],
       [13, 49, 77, 90],
       [42, 66, 88, 94],
       [ 1,  2, 73, 81]])

In [10]:
# sort by column we can use axis = 1
np.sort(b,axis = 1)

array([[ 6, 40, 84, 95],
       [43, 51, 71, 85],
       [11, 17, 36, 88],
       [13, 49, 77, 90],
       [42, 66, 88, 94],
       [ 1,  2, 73, 81]])

In [12]:
# sort by row we use axis = 0
print(b)
np.sort(b, axis = 0)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[ 6,  2, 11,  1],
       [13, 36, 77, 17],
       [43, 40, 81, 42],
       [73, 51, 84, 49],
       [88, 66, 85, 71],
       [94, 90, 88, 95]])

In [14]:
# for decending sorting
# use [::-1]
print(a)
np.sort(a)[::-1]

[24  1  9 91 56 84 57 94 27 73 91 21 79 93 19]


array([94, 93, 91, 91, 84, 79, 73, 57, 56, 27, 24, 21, 19,  9,  1])

In [18]:
# for decending sorting
# use [::-1]
print(b)
np.sort(b)[::-1]

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[ 1,  2, 73, 81],
       [42, 66, 88, 94],
       [13, 49, 77, 90],
       [11, 17, 36, 88],
       [43, 51, 71, 85],
       [ 6, 40, 84, 95]])

In [19]:
# for decending sorting
# use [::-1]
print(b)
np.sort(b,axis = 0)[::-1]

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[94, 90, 88, 95],
       [88, 66, 85, 71],
       [73, 51, 84, 49],
       [43, 40, 81, 42],
       [13, 36, 77, 17],
       [ 6,  2, 11,  1]])

# np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [21]:
# code
print(a)
np.append(a,200)

[24  1  9 91 56 84 57 94 27 73 91 21 79 93 19]


array([ 24,   1,   9,  91,  56,  84,  57,  94,  27,  73,  91,  21,  79,
        93,  19, 200])

In [23]:
# add one more column 
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 6., 40., 84., 95.,  1.],
       [43., 51., 85., 71.,  1.],
       [88., 36., 11., 17.,  1.],
       [13., 90., 77., 49.,  1.],
       [94., 66., 88., 42.,  1.],
       [73.,  2., 81.,  1.,  1.]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [24]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [58]:
# '1' is use for rowwise addition
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
# '0' is use for columnwise addition
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [31]:
# code
e = ([1,2,3,3,2,4,5,5,4,6,6,6,1])

In [32]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [39]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [38]:
np.expand_dims(a,axis = 0)

array([[24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19]])

In [40]:
np.expand_dims(a,axis = 1)

array([[24],
       [ 1],
       [ 9],
       [91],
       [56],
       [84],
       [57],
       [94],
       [27],
       [73],
       [91],
       [21],
       [79],
       [93],
       [19]])

In [41]:
np.expand_dims(a,axis = 0).shape

(1, 15)

# np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [42]:
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [44]:
# find all indexex which is greater than 50
np.where(a>50)

(array([ 3,  4,  5,  6,  7,  9, 10, 12, 13], dtype=int64),)

In [45]:
# replace all values >50 with 0
# write code on below basis
# # np.where(condition,true,false)
np.where(a>50,0,a)

array([24,  1,  9,  0,  0,  0,  0,  0, 27,  0,  0, 21,  0,  0, 19])

In [47]:
# replace all values < 50 with 'P'
np.where(a<50,'P',a)

array(['P', 'P', 'P', '91', '56', '84', '57', '94', 'P', '73', '91', 'P',
       '79', '93', 'P'], dtype='<U11')

In [50]:
# replace all the values divisable by 2 with 0
np.where(a%2 == 0,0,a)

array([ 0,  1,  9, 91,  0,  0, 57,  0, 27, 73, 91, 21, 79, 93, 19])

In [55]:
# replace all the values divisable by 3 with 0
np.where(a%3 == 0,0,a)

array([ 0,  1,  0, 91, 56,  0,  0, 94,  0, 73, 91,  0, 79,  0, 19])

# np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [57]:
# by this we find max value form the array
print(a)
np.argmax(a)

[24  1  9 91 56 84 57 94 27 73 91 21 79 93 19]


7

In [61]:
# by this we find max value form the array 
# we find first rowwise (use axis = 1)
print(b)
np.argmax(b,axis = 1)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([3, 2, 0, 1, 0, 2], dtype=int64)

In [63]:
# by this we find max value form the array 
# we find first columnwise (use axis = 0 )
print(b)
np.argmax(b,axis = 0)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([4, 3, 4, 0], dtype=int64)

In [65]:
# we also find minimum value
print(b)
np.argmin(b, axis = 0)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([0, 5, 2, 5], dtype=int64)

# np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [66]:
print(a)
np.cumsum(a)

[24  1  9 91 56 84 57 94 27 73 91 21 79 93 19]


array([ 24,  25,  34, 125, 181, 265, 322, 416, 443, 516, 607, 628, 707,
       800, 819], dtype=int32)

In [72]:
print(b)
np.cumsum(b)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([   6,   46,  130,  225,  268,  319,  404,  475,  563,  599,  610,
        627,  640,  730,  807,  856,  950, 1016, 1104, 1146, 1219, 1221,
       1302, 1303], dtype=int32)

In [73]:
print(b)
np.cumsum(b,axis = 0)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[  6,  40,  84,  95],
       [ 49,  91, 169, 166],
       [137, 127, 180, 183],
       [150, 217, 257, 232],
       [244, 283, 345, 274],
       [317, 285, 426, 275]], dtype=int32)

In [74]:
print(b)
np.cumsum(b,axis = 1)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[  6,  46, 130, 225],
       [ 43,  94, 179, 250],
       [ 88, 124, 135, 152],
       [ 13, 103, 180, 229],
       [ 94, 160, 248, 290],
       [ 73,  75, 156, 157]], dtype=int32)

In [75]:
# np.cumprod
## it is basically use for multiplication

print(a)
np.cumprod(a)

[24  1  9 91 56 84 57 94 27 73 91 21 79 93 19]


array([         24,          24,         216,       19656,     1100736,
          92461824,   975356672,  1489213952,  1554071040,  1778036224,
       -1407460864,   508092928,  1484635648,   632161792,  -873827840],
      dtype=int32)

# np.percentile

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [76]:
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [77]:
np.percentile(a,100)

94.0

In [78]:
np.percentile(a,50)

57.0

# np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [79]:
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [80]:
np.histogram(a,bins = [10,20,30,40,50])

(array([1, 3, 0, 0], dtype=int64), array([10, 20, 30, 40, 50]))

# np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [81]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [82]:
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [90]:
items = 10,91,84,40,1
np.isin(a,items)

array([False,  True, False,  True, False,  True, False, False, False,
       False,  True, False, False, False, False])

In [89]:
items = 10,91,84,40,1
a[np.isin(a,items)]

array([ 1, 91, 84, 91])

# np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [91]:
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [92]:
np.flip(a)

array([19, 93, 79, 21, 91, 73, 27, 94, 57, 84, 56, 91,  9,  1, 24])

In [93]:
print(b)
np.flip(b)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[ 1, 81,  2, 73],
       [42, 88, 66, 94],
       [49, 77, 90, 13],
       [17, 11, 36, 88],
       [71, 85, 51, 43],
       [95, 84, 40,  6]])

In [95]:
# for column fliping use axis = 0
print(b)
np.flip(b,axis = 0)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[73,  2, 81,  1],
       [94, 66, 88, 42],
       [13, 90, 77, 49],
       [88, 36, 11, 17],
       [43, 51, 85, 71],
       [ 6, 40, 84, 95]])

In [97]:
# for row fliping use axis = 1
print(b)
np.flip(b,axis = 1)

[[ 6 40 84 95]
 [43 51 85 71]
 [88 36 11 17]
 [13 90 77 49]
 [94 66 88 42]
 [73  2 81  1]]


array([[95, 84, 40,  6],
       [71, 85, 51, 43],
       [17, 11, 36, 88],
       [49, 77, 90, 13],
       [42, 88, 66, 94],
       [ 1, 81,  2, 73]])

# np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [112]:
# code
z = np.random.randint(10,50,10)
print(z)

np.put(z,[0,1],[32,33])
print(z)

[28 21 36 34 17 26 25 23 37 39]
[32 33 36 34 17 26 25 23 37 39]


# np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [114]:
print(z)
# for deleting single value
np.delete(z,0)

[32 33 36 34 17 26 25 23 37 39]


array([33, 36, 34, 17, 26, 25, 23, 37, 39])

In [116]:
print(z)
# for deleting multiple value
np.delete(z,[0,2,4])

[32 33 36 34 17 26 25 23 37 39]


array([33, 34, 26, 25, 23, 37, 39])

# set function

np.union1d

np.intersect1d

np.setdiff1d

np.setxor1d

np.in1d

In [117]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [118]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.intersect1d(m,n)

array([3, 4, 5])

In [119]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.setdiff1d(m,n)

array([1, 2])

In [120]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.setxor1d(m,n)

array([1, 2, 6, 7])

In [121]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.in1d(m,n)

array([False, False,  True,  True,  True])

In [123]:
m[np.in1d(m,1)]

array([1])

# np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [124]:
a

array([24,  1,  9, 91, 56, 84, 57, 94, 27, 73, 91, 21, 79, 93, 19])

In [125]:
np.clip(a,a_min = 25,a_max = 75)

array([25, 25, 25, 75, 56, 75, 57, 75, 27, 73, 75, 25, 75, 75, 25])